-- MySQL Script generated by MySQL Workbench
-- mié 01 mar 2017 11:40:39 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pisos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pisos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pisos` DEFAULT CHARACTER SET utf8 ;
USE `pisos` ;

-- -----------------------------------------------------
-- Table `pisos`.`pisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pisos`.`pisos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(100) NOT NULL,
  `precio` INT(3) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
